# Generated by Django 2.2.5 on 2020-01-26 00:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MovieData2018',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movie_name', models.CharField(max_length=128, verbose_name='电影名')),
                ('movie_orig_name', models.CharField(max_length=128, verbose_name='别名')),
                ('movie_rate', models.FloatField(default=0, verbose_name='得分')),
                ('movie_url', models.CharField(max_length=128, unique=True, verbose_name='相关豆瓣地址')),
                ('movie_type', models.CharField(max_length=128, verbose_name='所属类型')),
                ('c_time', models.DateTimeField(auto_now_add=True, verbose_name='添加时间')),
            ],
            options={
                'verbose_name': '2018年度榜单',
                'verbose_name_plural': '2018年度榜单',
                'db_table': '2018MovieData',
                'ordering': ['c_time'],
            },
        ),
        migrations.CreateModel(
            name='MovieData2019',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movie_name', models.CharField(max_length=128, verbose_name='电影名')),
                ('movie_orig_name', models.CharField(max_length=128, verbose_name='别名')),
                ('movie_rate', models.FloatField(default=0, verbose_name='得分')),
                ('movie_url', models.CharField(max_length=128, unique=True, verbose_name='相关豆瓣地址')),
                ('movie_type', models.CharField(max_length=128, verbose_name='所属类型')),
                ('c_time', models.DateTimeField(auto_now_add=True, verbose_name='添加时间')),
            ],
            options={
                'verbose_name': '2019年度榜单',
                'verbose_name_plural': '2019年度榜单',
                'db_table': '2019MovieData',
                'ordering': ['c_time'],
            },
        ),
    ]
