# Generated by Django 2.2.5 on 2020-02-07 00:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_integration', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='moviedata2018',
            name='movie_url',
            field=models.CharField(max_length=128, verbose_name='相关豆瓣地址'),
        ),
        migrations.AlterField(
            model_name='moviedata2019',
            name='movie_url',
            field=models.CharField(max_length=128, verbose_name='相关豆瓣地址'),
        ),
    ]
